### PR TITLE
add two additional arguments, VIPB and VIA

### PR DESCRIPTION
**Pull request by smithed**
So I couldn't figure out how to do the squash thing with the tool I use (sorry, I hate tortoise) and I also couldn't get it working from the command line. It also warned me not to try to squash commits I've already pushed, so it was too late anyhow.

That having been said I manually merged your changes with mine and nothing seems broken. I basically erred on the side of using all of your changes since there were not a ton, and then reapplied my changes where necessary (basically build action and thats it)

original pull request had this text:
new commands:
First is "VIA" which is the same as "VI" except is passes any extra arguments to an array-of-strings control called "args" on the front panel of the called vi. <edit: I also added the item you added to the original VI call>
Second is "VIPB" which is a vastly more complicated version of "VIP" and includes installing dependencies, making sure the code to be built is uninstalled, and then installing and uploading the resultant package to a repository. 

"VIPB" is more complex and has the following flags:
nopostbuild->no post build steps
nouninst->doesn't matter if package is already installed in system
nodeps->ignore dependencies, just build as-is
depversion="1.2.3.4"->tells tool to make sure a specific version of the package is used to gather up dependencies, ie for legacy builds or branches
noaddtolocallib->dont add to the package library on the build machine, may interfere with later builds
testinstall->install immediately after building to make sure it works, skipped if this flag isnt present.
[any number of these allowed]upload="reponame"->tells the build to add the new package to a specific repository. Build machine must be able to manage repos.

My most common command looks like this:
vipb    source\BLAH.vipb    testinstall upload=MyRepo

### CODE REVIEW

**Comment by BarrettStephen** [comment]
You can squash commits you have already pushed. you just need to squash them on your computer then force push them up. there is a 'force only known changes' flag you can use to do it safely. I have done this a few times when I mistakenly pushed non-squashed commits. If you watch that NI Tech presentation I gave you, Joe shows how to use the command line to do this.

Thanks so much for managing the merge and getting this all back together. Really appreciate it.

**Comment by BarrettStephen** [comment]
Before I merge this, I noticed you have it saved back to 2010. Can you explain why? The oldest LV I use is 2011 since 2010 is no longer supported. Therefore if I need to make changes to this in the future I will use 2011... which kinda hoses you

**Comment by smithed** [comment]
Yeah I tried doing the interactive rebase stuff from the command line and couldn't get it to work, but I'll give it another go later.

I would also open the code on your end and make sure it looks like I kept all of your changes.

As for 2010, I just saved it to 2010 cause that was the earliest the script seemed to support. I'm only using 2013 and newer, so 2011 is just fine for my purposes.

**Comment by BarrettStephen** [comment]
ok great. i guess in the future we dont have to deal with saving back to 2010.

looks great. only thing I would ask to change is all the flat sequence structures with error wired to them. what purpose are they serving?

**Comment by smithed** [comment]
They clear errors without using clear errors. Since they're inline, as I understand it lv can do a better job of optimizing out any error generating code. In other words I used them out of habit, not because they are inherently superior to another option in this situation.

**Comment by BarrettStephen** [comment]
interesting. learned something new! 
ill merge this in now and test that my autobuild system still works as expected this afternoon.

thanks

**Pull request merged**
